//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dasigno.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlStatement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlStatement() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dasigno.Api.Resources.SqlStatement", typeof(SqlStatement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE DATABASE bddasigno.
        /// </summary>
        internal static string CreateBd {
            get {
                return ResourceManager.GetString("CreateBd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE TABLE Error (
        ///    Id SERIAL PRIMARY KEY,
        ///    Source VARCHAR(255),
        ///    Message TEXT,
        ///    MessageDetail TEXT
        ///);.
        /// </summary>
        internal static string CreateTableError {
            get {
                return ResourceManager.GetString("CreateTableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE TABLE Users (
        ///    Id SERIAL PRIMARY KEY,
        ///    FirstName VARCHAR(255),
        ///    SecondName VARCHAR(255),
        ///    Surname VARCHAR(255),
        ///    SecondSurname VARCHAR(255),
        ///    BirthdayDate VARCHAR(255),
        ///    Remove BOOLEAN NOT NULL DEFAULT false,
        ///    Salary FLOAT,
        ///    CreateOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        ///    UpdateOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ///);
        ///.
        /// </summary>
        internal static string CreateTableUser {
            get {
                return ResourceManager.GetString("CreateTableUser", resourceCulture);
            }
        }
    }
}
